MODEL_NAME = "vae_celeba_1"
MODEL_DIR  = "./models/"

DATASET_NAME = "CelebA"
DATASET_DIR  = "../pytorch-datasets/"
SUBSET_SIZE  = 0 # set to zero for full dataset

EPOCHS        = 1
LEARNING_RATE = 1 / 1024 

MSE_WEIGHT = 1
KLD_WEIGHT = 1 / 32768

BATCH_SIZE = 64
IMG_DEPTH  = 3
IMG_HEIGHT = 64
IMG_WIDTH  = 64

INPUT_SHAPE = [BATCH_SIZE, IMG_DEPTH, IMG_HEIGHT, IMG_WIDTH]

CONV_CHANNELS = [2*IMG_DEPTH, 4*IMG_DEPTH, 8*IMG_DEPTH, 16*IMG_DEPTH]
FFN_LAYERS    = [128*IMG_DEPTH, 64*IMG_DEPTH, 32*IMG_DEPTH]
LATENT_SIZE   = 16*IMG_DEPTH
